name: Build Minecraft Plugin

on:
  push:
    branches: [ "main", "master" ] # Сборка сработает при пуше в эти ветки

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      # Флаг --file pom.xml гарантирует, что Maven найдет конфиг в корне
      run: mvn -B package --file pom.xml

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: CreateCountry-Jar-File
        path: target/*.jar
